function [fitresult, gof] = createTMresponseFit(x, y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'set1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Feb-2016 22:04:35


%% Fit: 'set1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'rat55' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Algorithm = 'Levenberg-Marquardt';
opts.Display = 'Off';
opts.StartPoint = [0.121042689821443 0.810343230977348 0.828375197722307 0.744837762348882 0.91957258291654 0.382420968540841 0.242824124465619 0.118839727107912 0.43440650906428 0.140040566767786 0.768238174523116];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );



